### ISSUE TITLE
why the patch libbpf-introduce-legacy-kprobe-events-support.patch is needed?

### ISSUE THREAD

**Issue by rainkin1993** [rafaeldtinoco/conntracker#4]
Hi. This is a great work to let old kernel supports CO-RE.
I notice that a patch is applied, e.g., libbpf-introduce-legacy-kprobe-events-support.patch. 
Can I ask why this patch is necessary? I think libbpf already supports kprobes.

One more question: where is the function bpftracker_bpf__load defined?
Thanks

**Comment by rafaeldtinoco** [comment]
Hello, thanks! 

The libbpf supports kprobes through the new  kernels interface, not the old one (described by my perf_event_open_probe_legacy() function). This patch is an attempt to add CO.RE functionality to older kernels (like v4.15, still being used in Ubuntu Bionic). 

> This is being discussed in the upstream [mailing list](https://lore.kernel.org/bpf/20210322180441.1364511-1-rafaeldtinoco@ubuntu.com/). It has not yet been accepted because I need to finish the legacy kprobe 'unloading' logic [HERE[(https://github.com/rafaeldtinoco/conntracker/blob/main/ebpf/patches/libbpf-introduce-legacy-kprobe-events-support.patch#L440). I need to use put my unloading logic inside upstream maps unloading logic.

One more question: where is the function bpftracker_bpf__load defined?

This is part of the libbpf skeleton logic creation, done by the **bpftool** declared in the Makefile. If you allow me, a better place for you to understand this would be my [portablebpf repository](https://github.com/rafaeldtinoco/portablebpf), a place where I keep the ebpf part away from anything else (and just like the one being used in conntracker). README.md contains explanations that might help you out.

**Comment by rainkin1993** [comment]
Thanks for your answer.

> The libbpf supports kprobes through the new kernels interface, not the old one (described by my perf_event_open_probe_legacy() function). This patch is an attempt to add CO.RE functionality to older kernels (like v4.15, still being used in Ubuntu Bionic).
Would you mind explaining which new kernels interface is used? 
I read the perf_event_open_probe_legacy(),  it seems perf_event_open syscall is the main difference. But I am not sure this is what you mean.
`+	attr.size = sizeof(attr);
+	attr.config = type;
+	attr.type = PERF_TYPE_TRACEPOINT;
+
+	pfd = syscall(__NR_perf_event_open,
+		      &attr,
+		      pid < 0 ? -1 : pid,
+		      pid == -1 ? 0 : -1,
+		      -1,
+		      PERF_FLAG_FD_CLOEXEC);`
